services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  ros:
    build:
      context: ros
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
